--
-- Table structure for table `t_audio`
-- 
CREATE TABLE `t_audio` (
  `ID_AUDIO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CATEGORY` int(11) DEFAULT NULL,
  `ID_AUTHOR` int(11) DEFAULT NULL,
  `ID_SOURCE` int(11) DEFAULT NULL,
  `A_NAME` varchar(255) DEFAULT NULL,
  `A_E_NAME` varchar(255) DEFAULT NULL,
  `A_COVER` varchar(255) DEFAULT NULL,
  `A_TRACKS` int(11) DEFAULT NULL,
  `A_SIZE` double DEFAULT '0',
  `A_RECOMMEND` varchar(45) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT NULL,
  `CREATEUSER` varchar(45) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT NULL,
  `UPDATEUSER` varchar(45) DEFAULT NULL,
  `IS_ACTIVE` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID_AUDIO`)
);

--
-- Table structure for table `t_author`
--
CREATE TABLE `t_author` (
  `ID_AUTHOR` int(11) NOT NULL AUTO_INCREMENT,
  `AU_NAME` varchar(45) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT NULL,
  `CREATEUSER` varchar(45) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT NULL,
  `UPDATEUSER` varchar(45) DEFAULT NULL,
  `IS_ACTIVE` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID_AUTHOR`)
);

--
-- Table structure for table `t_category`
--
CREATE TABLE `t_category` (
  `ID_CATEGORY` int(11) NOT NULL AUTO_INCREMENT,
  `C_NAME` varchar(255) DEFAULT NULL,
  `C_TYPE` varchar(45) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT NULL,
  `CREATEUSER` varchar(45) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT NULL,
  `UPDATEUSER` varchar(45) DEFAULT NULL,
  `IS_ACTIVE` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID_CATEGORY`)
);
--
-- Dumping data for table `t_category`
--

CREATE TABLE `t_recording` (
  `ID_RECORDING` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SUB_AUDIO` int(11) DEFAULT NULL,
  `ID_WXUSER` INT(11) NULL DEFAULT NULL,
  `R_SEQ_NO` INT(2) NULL DEFAULT 0,
  `R_RECORD_TIME` datetime DEFAULT NULL,
  `R_FILE_PATH` VARCHAR(255) NULL,
  `R_FILE_SIZE` varchar(255) DEFAULT NULL,
  `R_CLIENTIP` varchar(45) DEFAULT NULL,
  `R_CLIENTAPP` varchar(45) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT NULL,
  `CREATEUSER` varchar(45) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT NULL,
  `UPDATEUSER` varchar(45) DEFAULT NULL,
  `IS_ACTIVE` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID_RECORDING`)
);
--
-- Table structure for table `t_source`
--
CREATE TABLE `t_source` (
  `ID_SOURCE` int(11) NOT NULL AUTO_INCREMENT,
  `S_YEAR` varchar(45) DEFAULT NULL,
  `S_NAME` varchar(255) DEFAULT NULL,
  `S_TYPE` varchar(45) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT NULL,
  `CREATEUSER` varchar(45) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT NULL,
  `UPDATEUSER` varchar(45) DEFAULT NULL,
  `IS_ACTIVE` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID_SOURCE`)
);
--
-- Table structure for table `t_sub_audio`
--

CREATE TABLE `t_sub_audio` (
  `ID_SUB_AUDIO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_AUDIO` int(11) DEFAULT NULL,
  `SUB_AUDIO_TYPE` int(11) DEFAULT NULL,
  `SUB_AUDIO_ROLE` int(11) DEFAULT NULL,
  `SUB_AUDIO_ROLE_COMMENT` VARCHAR(45) DEFAULT NULL,
  `SUB_AUDIO_INDEX` int(11) DEFAULT NULL,
  `SUB_AUDIO_LENGTH` int(11) DEFAULT NULL,
  `SUB_AUDIO_LRC` VARCHAR(255) NULL,
  `A_FILE_PATH` varchar(255) DEFAULT NULL,
  `A_SIZE` double DEFAULT '0',
  `A_RECOMMEND` varchar(45) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT NULL,
  `CREATEUSER` varchar(45) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT NULL,
  `UPDATEUSER` varchar(45) DEFAULT NULL,
  `IS_ACTIVE` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID_SUB_AUDIO`)
);
--
-- Table structure for table `t_user`
--

CREATE TABLE `t_user` (
  `ID_USER` int(11) NOT NULL AUTO_INCREMENT,
  `U_NAME` varchar(45) DEFAULT NULL,
  `U_NICKNAME` varchar(45) DEFAULT NULL,
  `U_LOGIN_ID` varchar(20) DEFAULT NULL,
  `U_PASSWORD` varchar(20) DEFAULT NULL,
  `U_AGE` int(11) DEFAULT '0',
  `U_SEX` varchar(2) DEFAULT NULL,
  `U_REGIST_TIME` datetime DEFAULT NULL,
  `U_REGIST_IP` varchar(45) DEFAULT NULL,
  `U_EMAIL` varchar(128) DEFAULT NULL,
  `U_PHONE` varchar(20) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT NULL,
  `CREATEUSER` varchar(45) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT NULL,
  `UPDATEUSER` varchar(45) DEFAULT NULL,
  `IS_ACTIVE` int(11) DEFAULT '1',
  PRIMARY KEY (`ID_USER`)
);

CREATE TABLE `t_wxuser` (
  `ID_WXUSER` INT NOT NULL AUTO_INCREMENT,
  `U_OPENID` VARCHAR(255) NULL,
  `U_NICKNAME` VARCHAR(255) NULL,
  `U_PROVINCE` VARCHAR(255) NULL,
  `U_COUNTRY` VARCHAR(255) NULL,
  `U_CITY` VARCHAR(255) NULL,
  `U_AVATARURL` VARCHAR(255) NULL,
  `U_GENDER` INT(2) NULL DEFAULT 0,
  `CREATETIME` DATETIME NULL DEFAULT NULL,
  `CREATEUSER` VARCHAR(45) DEFAULT NULL,
  `UPDATETIME` DATETIME NULL DEFAULT NULL,
  `UPDATEUSER` VARCHAR(45) NULL DEFAULT NULL,
  `IS_ACTIVE` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID_WXUSER`)
  );
